### ISSUE TITLE
Reserve Pool Divide by Zero

### ISSUE THREAD

**Issue by ShynRou** [Frankencoin-ZCHF/FrankenCoin#1]
The following lines lead to read call reverts, hindering the front end from loading multiple things at once.
In this case not super bad because the Reserve Pool should never be at 0 except for directly after deployment. But I'd appreciate if you take care to avoid something like this in the other contracts. 

https://github.com/Frankencoin-ZCHF/FrankenCoin/blob/b1eefd6ce8721e13807f944c01b54e3daa31efbc/contracts/ReservePool.sol#L47

https://github.com/Frankencoin-ZCHF/FrankenCoin/blob/b1eefd6ce8721e13807f944c01b54e3daa31efbc/contracts/ReservePool.sol#L151

**Comment by luziusmeisser** [comment]
won't happen once the first share has been minted
