### ISSUE TITLE
Data API

### ISSUE THREAD

**Issue by TaprootFreak** [Frankencoin-ZCHF/FrankenCoin#25]
I think it would be important to have a simple API that provides the most important data. Similar to what DFX does with this link:

https://dev.api.dfx.swiss/v1/frankencoin/info

Perhaps it already exists and I just haven't found it, in which case I would be happy to receive a tip on where I can find it.

**Comment by samclassix** [comment]
discussion and issue moved to: https://github.com/Frankencoin-ZCHF/frankencoin-api/issues/1
